name: Scrapy Automation

on:
  schedule:
    - cron: "0 11 * * 1"  # Segunda-feira às 11h UTC
    - cron: "0 13 * * 1"  # Segunda-feira às 13h UTC
  workflow_dispatch:  # Permite execução manual

jobs:
  run-spiders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar ambiente Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Rodar script que aciona os spiders
        run: python run_scrappers.py  

      - name: Salvar arquivos gerados
        uses: actions/upload-artifact@v4
        with:
          name: scraped-data
          path: archive/*.csv  # Salva todos os arquivos CSV gerados

  insert-data:
    runs-on: ubuntu-latest
    needs: run-spiders  # Espera o primeiro job terminar antes de rodar
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar ambiente Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Baixar arquivos gerados
        uses: actions/download-artifact@v4
        with:
          name: scraped-data
          path: archive/  # Baixa os arquivos na pasta correta

      - name: Rodar script que popula planilhas
        run: python push_sheets.py  
