---
  name: Scrapy Automation
  
  on:
    schedule:
      - cron: "0 11 * * 1"  # Segunda-feira às 11h UTC
      - cron: "0 13 * * 1"  # Segunda-feira às 13h UTC
    workflow_dispatch:  # Permite execução manual
  
  jobs:
    run-spiders:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout do código
          uses: actions/checkout@v4
  
        - name: Configurar ambiente Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.12"
  
        - name: Instalar dependências
          run: pip install -r requirements.txt
  
        - name: Rodar script que aciona os spiders
          run: python script/run_scrappers.py  
  
    insert-data:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout do código
          uses: actions/checkout@v4
  
        - name: Configurar ambiente Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.12"
  
        - name: Instalar dependências
          run: pip install -r requirements.txt

        - name: Listar arquivos do repositório
          run: ls -R
  
        - name: Rodar script que popula planilhas
          run: python script/push_sheets.py    